### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Starblaster64** [Chdata/Versus-Saxton-Hale#14]
### Developing

Ticked box means that it's finished but not yet published. Version number denotes when it will (probably) be added to the plugin.
- [ ] Re-organise `TF2Items_OnGiveNamedItem` weapon list into weapon slots and classes
- [ ] Make newdecls optional
- [ ] Add support for Jungle Inferno Update. [Issue](30)
  - [ ] Balance new Pyro weapons. [Issue](31)
- [ ] Add support for Meet your Match update. [Issue](28)
- [ ] Fix backstab animations
- [ ] Implement Super Hale?
- [ ] Implement higher sensitivity super jumping.
- [ ] Make PrepareModel write errorlogs if it doesn't find a file, because really if you are missing any one file for any of the models then you're going to have a problem you need to fix, except for bunny if you don't use him. And it helps if the plugin can tell you that's what's wrong.
- [ ] Fix /hale_voice and make a standard for it. [Issue](7)
- [ ] Change SearchForItemPacks() to demote ammo packs only down to a Medium pack (with a CVAR).
- [ ] Re-add Quickfix attribute to Mediguns with CVAR.
- [ ] Set mp_blockstyle to 0 by default. Cap blocks will reset cap time instead of pausing it (with a CVAR?).
- [ ] Nerf Demo boots' speed boost for players using the Eyelander.
- [ ] Fix English translation files so class info panels don't overflow.
  - [ ] Alternatively, upgrade to a Custom Weapons style menu that only shows info for currently equipped weapons.
- [ ] Update non-English translation files (seriously out of date).
- [ ] Fix players spawning mid-round receiving last-man standing bonuses. [Issue](16)
- [ ] Change spook movespeed penalty on Scouts from -25% back to -50%.
- [x] Modify SpawnRandomAmmo() and SpawnRandomHealth() to generate at least 1 medium health & ammo pack.
- [x] Add support for the Tough Break update. [Issue](18)
- [x] Fix Rocket Jumper not being replaced correctly. [Pull Request](17)
- [x] Fix Shananashaha not having correct damage. [Pull Request](17)
- [x] Future proof Sniper Rifles (again). [Pull Request](20)
- [x] Add mini-crits on airborne targets to the Cow Mangler 5000 [Pull Request](17)
- [x] Fix addthecrit not applying properly to throwables. (1.56) [Pull Request](9)
- [x] Re-work Ubercharge. (1.56) [Pull Request](12)
- [x] Add support for different arena preround times. (1.56) [Pull Request](13)
- [x] tf_spec_xray set to 2 by default. (1.56) [Issue](10)
- [x] Fix Shortstop having wrong attributes (Valve changed some attributes apparently). [Pull Request](17)
### Under Consideration

If it's crossed out, it was declined.
#### Non-Weapon Changes
- Nerf Super-Jump
- Buff Heavy, somehow
- Apply Anchor to Hale while swimming
- Modify behaviour of Control Points. (Hale capping will teleport remaining opponents to the point, non-Hales capping will still win the round)
- Outline last man standing, like in FF2.
- ~~Silence Administrator lines~~ [Pull Request](13)
#### Weapon Changes
- KGB adds X seconds of crits instead of being a GRU reskin.
- Add +10% Über on Hit attribute to the Third Degree to better indicate its ability
- Re-work Backburner
- Nerf Scorch Shot
- Nerf Mega-Detonator's self push force from +220% to +150%
- Change Wallclimb ability to not work on Clip brushes [Pull Request](15)
- Give the Righteous Bison shotgun bonuses.
- Give Scorch Shot mini-crit on burning players attribute.
- Quickie-Bomb Launcher mini-crits on airborne targets.
- Make modified Mediguns compatible with vanity features. [Issue](21) (Probably not feasible)
- Nerf Pyro's airblast
- Various suggestions featured in the VSH Steam Group discussion page: [http://steamcommunity.com/groups/VsSaxtonHale/discussions/0/619569341013432142/](http://steamcommunity.com/groups/VsSaxtonHale/discussions/0/619569341013432142/)
  - BFB
  - Soda Popper
  - Buff Banner
  - Spy-Cicle
  - Some other ones.
### Finished

Stuff that's been completed and added in the denoted version of VSH.
- Starblaster64's future proofing of various crit weapons. (1.55) [Pull Request](4)
- Add wrappers to the convars to prevent people from changing them mid round. (1.55)

**Comment by Starblaster64** [comment]
- [ ] Implement Super Hale.
- [ ] Implement higher sensitivity super jumping.
- [x] Add wrappers to the convars to prevent people from changing them mid round.
- [x] Starblaster64's future proofing of various crit weapons.
- [ ] Make PrepareModel write errorlogs if it doesn't find a file, because really if you are missing any one file for any of the models then you're going to have a problem you need to fix, except for bunny if you don't use him. And it helps if the plugin can tell you that's what's wrong.
- [ ] Fix /hale_voice and make a standard for it
- [x] Re-worked Ubercharge
- [x] Add support for different arena preround times

**Comment by Chdata** [comment]
Doesn't scorch shot have full crits anyway

**Comment by Chdata** [comment]
Under consideration: Buff Banner, Soda Popper, BFB, Spy-Cycle, etc changes.

http://steamcommunity.com/groups/VsSaxtonHale/discussions/0/619569341013432142/

**Comment by Starblaster64** [comment]
We went through this before, it only affects Phlog Pyros.

**Comment by Starblaster64** [comment]
Was skimming through the VSH Suggestions discussion, saw something about applying Anchor on Hales who are swimming. Just wanted to bring it up in-case you forgot about adding that to the public branch.

**Comment by Chdata** [comment]
i've been working on trying to fix some bugs with my anchor
